--decimal(Numeric precision, Numeric scale)
--	precision: Total number of digits (before + after the decimal point).
--scale: Number of digits after the decimal point.
CREATE TABLE MyTable (
MyDecimalColumn decimal (5,2), 
MyNumberColumn numeric (10,5)
);

--DROP TABLE MyTable
SELECT * FROM MyTable

INSERT INTO MyTable VALUES (123,1234.12);
INSERT INTO MyTable VALUES (123.12345, 12345);
INSERT INTO MyTable VALUES (123.12345, -12345.123456);
INSERT INTO MyTable VALUES (123.12645, -12345.123456);
INSERT INTO MyTable VALUES (123.12545, -12345.123456);
INSERT INTO MyTable VALUES (123.12545,-123456)

---- Create the OWNER table
--DROP TABLE SERVICE_REQUEST
--DROP TABLE SERVICE_CATEGORY
--DROP TABLE RESIDENTS
--DROP TABLE PROPERTY
--DROP TABLE OFFICE
--DROP TABLE OWNER
CREATE TABLE OWNER (
    OWNER_NUM CHAR(5) not null,
    LAST_NAME VARCHAR(50) NOT NULL,
    FIRST_NAME VARCHAR(50) NOT NULL,
    ADDRESS VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    ZIP_CODE VARCHAR(10)
);
ALTER TABLE OWNER
ADD CONSTRAINT PK_Owner PRIMARY KEY (OWNER_NUM)

-- Create the OFFICE table
CREATE TABLE OFFICE (
    OFFICE_NUM INT NOT NULL,
    OFFICE_NAME VARCHAR(100) NOT NULL,
    ADDRESS VARCHAR(100),
    AREA VARCHAR(50),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    ZIP_CODE VARCHAR(10)
);
ALTER TABLE OFFICE
ADD CONSTRAINT PK_Office PRIMARY KEY (OFFICE_NUM)

-- Create the PROPERTY table
CREATE TABLE PROPERTY (
    PROPERTY_ID INT  NOT NULL,
    OFFICE_NUM INT NOT NULL,
    ADDRESS VARCHAR(100) NOT NULL,
    SQR_FT INT,
    BDRMS INT,
    FLOORS INT,
    MONTHLY_RENT DECIMAL(10, 2),
	OWNER_NUM CHAR(5) NOT NULL,
	)


	ALTER TABLE PROPERTY
	ADD CONSTRAINT PK_PROPERTY PRIMARY KEY (PROPERTY_ID),
    CONSTRAINT FK_PROPERTY_OWNER FOREIGN KEY (OWNER_NUM) REFERENCES OWNER(OWNER_NUM),
    CONSTRAINT FK_PROPERTY_OFFICE FOREIGN KEY (OFFICE_NUM) REFERENCES OFFICE(OFFICE_NUM)


-- Create the RESIDENTS table
CREATE TABLE RESIDENTS (
    RESIDENT_ID INT NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    FIRST_NAME VARCHAR(50) NOT NULL,
    PROPERTY_ID INT NOT NULL
    
);
ALTER TABLE RESIDENTS 

ADD CONSTRAINT PK_Residents PRIMARY KEY (RESIDENT_ID),
CONSTRAINT FK_RESIDENT_PROPERTY FOREIGN KEY (PROPERTY_ID) REFERENCES PROPERTY(PROPERTY_ID)

-- Create the SERVICE_CATEGORY table
CREATE TABLE SERVICE_CATEGORY (
    CATEGORY_NUM INT NOT NULL,
    CATEGORY_DESCRIPTION VARCHAR(100) NOT NULL
);
ALTER TABLE SERVICE_CATEGORY
ADD CONSTRAINT PK_Service_Catgory PRIMARY KEY (CATEGORY_NUM)


-- Create the SERVICE_REQUEST table
CREATE TABLE SERVICE_REQUEST (
    SERVICE_ID INT NOT NULL,
    PROPERTY_ID INT NOT NULL,
    CATEGORY_NUM INT NOT NULL,
    OFFICE_NUM INT NOT NULL,
    DESCRIPTION VARCHAR(255),
    STATUS VARCHAR(200),
    EST_HOURS DECIMAL(5, 2),
    SPENT_HOURS DECIMAL(5, 2),
    NEXT_SERVICE_DATE DATE
    
);

ALTER TABLE SERVICE_REQUEST
ADD CONSTRAINT PK_Service_Request PRIMARY KEY (SERVICE_ID) ,
CONSTRAINT FK_SERVICE_REQUEST_PROPERTY FOREIGN KEY (PROPERTY_ID) REFERENCES PROPERTY(PROPERTY_ID),
    CONSTRAINT FK_SERVICE_REQUEST_CATEGORY FOREIGN KEY (CATEGORY_NUM) REFERENCES SERVICE_CATEGORY(CATEGORY_NUM),
    CONSTRAINT FK_SERVICE_REQUEST_OFFICE FOREIGN KEY (OFFICE_NUM) REFERENCES OFFICE(OFFICE_NUM)
